spring.application.name = CONFIGURATION-DEV-SERVER
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://localhost:8085/eureka/
